### ISSUE TITLE
Mismatch between text and image when describing Xcode Integration 

### ISSUE THREAD

**Issue by marcosgriselli** [spotify/XCLogParser#6]
On the [Xcode Integration](https://github.com/spotify/XCLogParser#xcode-integration) part of the documentation the text reads _"To do that, open the scheme editor in a project and expand the **"Build"** panel on the left side."_ while the image displays the script being added to the **"Run"** phase: 

<img width="1107" alt="post-action-run-script" src="https://user-images.githubusercontent.com/14804033/59159502-cff74500-8aa0-11e9-8813-d27f43429b6a.png">

I can send a PR but wanted to double check which phase it should be (or perhaps it works in both?). 

Thanks for the awesome tool 🙌

**Comment by BalestraPatrick** [comment]
Hey @marcosgriselli! 

You're right, there's a mismatch there. It should work no matter in which phase you add the post-action since the `xcactivitylog` is created after the build is complete, and `XCLogParser` will wait for it to show up on disk before parsing it. Feel free to open a PR with the same screenshot updated with the run script added to the "Build" phase instead 😄

**Comment by marcosgriselli** [comment]
Thanks for the clarification @BalestraPatrick. It seems like the screenshot was replaced on #3 and if it works on the **Run** phase as well then its not a real issue. I'll close this one :)
